name: Deploy

on:
  workflow_run:
    workflows: [ Validate ]
    branches: [ main ]
    types: [ completed ]

jobs:
  deploy-beta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify --panicOnWarning --buildDrafts

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy
        run: rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -J root@ssh.alvarezrosa.com" public/ root@10.0.0.2:/srv/beta.alvarezrosa.com

  deploy-production:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify --panicOnWarning

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy
        run: rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -J root@ssh.alvarezrosa.com" public/ root@10.0.0.2:/srv/david.alvarezrosa.com
